FEAT: CREATE CLASS ENDPOINTS
fis-g4/learning-microservice pull request #16
Opened 2023-11-29 18:05 UTC by ivamorgra

**Description:**

This pull request introduces several changes to the project. Here's a summary of the modifications:

_**General Changes:**_

- Added import for the mongoose library.
- Included a new route in the server/routes/class.ts file for handling class-related operations.
- Implemented CRUD operations for classes, including GET, POST, PUT, and DELETE methods.
- Updated the route for classes in the main application file (app.ts).
- Made adjustments to the server/routes/materials.ts file, adding a TODO comment about checking the author of the 
  material.
- Updated the server/types.d.ts file to include the ClassInputs interface.

**_Specific Changes in server/routes/class.ts:_**

- Added a new route to retrieve class details by ID (router.get("/:id")).
- Implemented a POST route for creating a new class (router.post("/")).
- Implemented a PUT route for updating class information (router.put("/:id")).
- Implemented a DELETE route for deleting a class (router.delete("/:id")).
- Included TODO comments for future enhancements.
- Specific Changes in server/routes/materials.ts:

Added a TODO comment in the router.put('/:id') route about checking the author of the material.
Included additional checks for various fields in the router.put('/:id') route.

**_Specific Changes in server/types.d.ts:_**

- Added the ClassInputs interface to define the expected input structure for class-related operations.

**_Checklist:_**
 

- [x]   Review the changes in app.ts and ensured that routes are correctly configured.

- [x]  Check the implementation of CRUD operations in server/routes/class.ts for correctness and adherence to best practices.

- [x]  Examine the adjustments made in server/routes/materials.ts for completeness and potential improvements.

- [x]  Verify hat the server/types.d.ts file accurately reflects the input structures for materials and classes.

 **_Functionality Testing:_**

-  Test the GET, POST, PUT, and DELETE operations for classes to ensure proper functionality.

-  Verify  that the TODO comments regarding user access checks and connection to the course microservice are addressed appropriately.

-  Ensure that the router.put('/:id') route in server/routes/materials.ts performs the necessary checks on the material author.

2023-11-29 18:07 UTC, ivamorgra commented
I can provide reviewer the JSON file I have used in POSTMAN

[Learning Micorservice.postman_class.json](https://github.com/fis-g4/learning-microservice/files/13504091/Learning.Micorservice.postman_class.json)

2023-11-30 09:30 UTC, TomasCB24 commented
> I can provide reviewer the JSON file I have used in POSTMAN

This postman file is badly exported, neither the methods nor the urls inside the existing methods are exported.

2023-11-30 09:37 UTC, TomasCB24 commented
The methods work fine, but you have to make the changes that I have been adding in each file

2023-11-30 09:37 UTC, TomasCB24 requested changes

2023-11-30 09:37 UTC, TomasCB24 commented on server/index.ts
> +app.use(API_VERSION + '/class', _class)
This should be '/classes' since it is a collection that is being referred to. Like '/materials'.

2023-11-30 09:37 UTC, TomasCB24 commented on server/routes/class.ts
> +import express, { Request, Response } from 'express'
The name of this .ts file must be "classes", if we follow the same philosophy of the "materials" file which is already revised

2023-11-30 09:37 UTC, TomasCB24 commented on server/routes/class.ts
> +    const classId = req.params.id
this classId can be removed, using 'req.params.id' directly on the following line

2023-11-30 09:37 UTC, TomasCB24 commented on server/routes/class.ts
> +    console.log(req.body)
Is this console.log necessary?

2023-11-30 09:37 UTC, TomasCB24 commented on server/routes/class.ts
> +    console.log(_class)
Is this console.log necessary?

2023-11-30 09:37 UTC, TomasCB24 commented on server/routes/class.ts
> +    console.log(title, description, order, file)
this too

2023-11-30 09:37 UTC, TomasCB24 commented on server/routes/class.ts
> +    const classId = req.params.id
this classId can be removed, using 'req.params.id' directly on the following line

2023-11-30 18:53 UTC, TomasCB24 approved these changes
all oke

2023-12-02 19:46 UTC, merged