FIX: REVIEW AND CORRECT CLASS ENDPOINTS
fis-g4/learning-microservice pull request #29
Opened 2023-12-16 13:41 UTC by ivamorgra

# Proposed Changes in Class Endpoints

## Description of Changes
In this pull request, I've made changes and revisions to the endpoints related to classes. The key modification is the addition of a specific middleware that uses JSON Web Token (JWT) to authorize the user before granting access to certain resources.

## Details of Changes
- Added a JWT authorization middleware to each class endpoint.
- Changes include verification of the JWT token to ensure the user is authenticated before processing the request.

## Actions for Reviewer
Before approving the pull request, please follow this checklist to ensure the changes work correctly in Postman:

- [ ] **Authentication:** Verify that JWT authorization is correctly implemented.
- [ ] **Endpoints:** Run Postman requests for each modified endpoint.
- [ ] **Valid Requests:** Ensure valid requests with a valid token are properly authorized.
- [ ] **Invalid Requests:** Confirm that invalid requests without a token or with an invalid token are appropriately rejected.
- [ ] **Error Handling:** Check that authorization errors are handled appropriately.

## Additional Notes
Please provide specific feedback on any issues you may identify during the review. Thank you.

2023-12-16 13:42 UTC, ivamorgra commented
I apologize for the initial commit, I confused the task number.

2023-12-16 15:38 UTC, migromarj requested changes
Good work @ivamorgra! I have commented some status codes that you are missing to check, and a change you should make on the endpoint defined for the POST operation.

If you can, move the task associated with this Pull Request in the project dashboard to In Review.

Make use in the app.ts file of a middleware to be able to parse multer errors due to large files (more than 1GB), you can take a look at how it is done with materials.

In case it is easier for you to fix the issue of status codes, endpoints, etc. I share with you a [new version of the OAS](https://app.swaggerhub.com/apis/mrarjona/learning-microservice/0.1.0#/) that I have just written and should be complete. Please let me know if you find any errors.

2023-12-16 15:38 UTC, mrarjona commented on server/routes/classes.ts
> +const ERROR_LOGIN = 'Unauthenticated: You are not logged in'
I think you can remove this constant, it is not used in this file.

2023-12-16 15:38 UTC, mrarjona commented on server/routes/classes.ts
> +            return res.status(200).json({ message: 'Class deleted successfully' })
For the correct deletion code it was defined in the OAS that the status code should be 204. You can look at the material delete operation to put it similar.

2023-12-16 15:38 UTC, mrarjona commented on server/routes/classes.ts
> +router.delete('/:id',authUser, async (req: Request, res: Response) => {
This operation must also take into account the status code 403.

2023-12-16 15:38 UTC, mrarjona commented on server/routes/classes.ts
> +router.put('/:id',authUser,upload.single('file'),async (req: Request, res: Response) => {
This operation must also take into account the status code 403.

2023-12-16 15:38 UTC, migromarj commented on server/routes/classes.ts
>      //TODO: Check if user is the author of the class
Delete this "TODO" when you are aware of status code 403.

2023-12-16 15:38 UTC, migromarj commented on server/routes/classes.ts
>          //TODO: Check if user is the author of the class
Delete this "TODO" when you are aware of status code 403.

2023-12-16 15:38 UTC, migromarj commented on server/routes/classes.ts
> +router.post('/',authUser, upload.single('file'), async (req: Request, res: Response) => {
With respect to the OAS defined, the endpoint associated to the POST must be "/classes/course/{courseId}" to know in which course the class is being uploaded.

2023-12-16 16:37 UTC, ivamorgra commented on server/routes/classes.ts
> +const ERROR_LOGIN = 'Unauthenticated: You are not logged in'
Yes!!! I changed the function to another file and I forgot this. Good point!

2023-12-16 16:38 UTC, ivamorgra commented on server/routes/classes.ts
> +            return res.status(200).json({ message: 'Class deleted successfully' })
Ok!

2023-12-16 17:04 UTC, ivamorgra commented
Thank you for the feedback @migromarj! Currently, I'm unable to implement the handling of 403 errors as it requires communication with the courses microservice, which is not yet in place. Once the necessary integration is completed, I'll ensure to incorporate proper handling for the 403 status code. Appreciate your understanding!

2023-12-16 18:31 UTC, migromarj commented
> Thank you for the feedback @migromarj! Currently, I'm unable to implement the handling of 403 errors as it requires communication with the courses microservice, which is not yet in place. Once the necessary integration is completed, I'll ensure to incorporate proper handling for the 403 status code. Appreciate your understanding!

You're absolutely right, I'll bear that in mind!

2023-12-17 13:46 UTC, migromarj approved these changes
Thank you for taking the suggestions into account @ivamorgra. I have accepted it, everything works correctly, but **before making the merge change the maximum file space from 5MB to 1GB**, I have left in a comment above the modifications to be made.

2023-12-17 13:46 UTC, migromarj commented on server/routes/classes.ts
> +        //fileSize: 1024 * 1024 * 1024, // 1 GB
Uncomment this line and delete the previous one to set a limit of 1GB and not 5MB.

2023-12-19 17:09 UTC, merged